CREATE TABLE lodging (
    lodgingid SERIAL,
    namelodging VARCHAR(50),
    country VARCHAR(50),
    street VARCHAR(100),
    numberstreet VARCHAR(100),
    city VARCHAR(50),
    state VARCHAR(50),
    codepostal INTEGER(50),
    coordinates INTEGER(200),
);

CREATE TABLE lodgingtype (
    lodgingtypeid SERIAL,
    lodgings VARCHAR(25),
    ownhomes VARCHAR(25),
);

CREATE TABLE typelodgings (
typelodging VARCHAR (50),
hotelnetwork bool,
typerooms JSONB,
numberfloor INTEGER,
numberapartment VARCHAR(25),
lift VARCHAR (25),
garage INTEGER,
numberofrooms INTEGER,
capacitymaxperson VARCHAR,
numberbathrooms INTEGER,
commonareas VARCHAR (100),
kitchen VARCHAR (100),
featuresspecial VARCHAR(200),
comforts VARCHAR,
aditionalservices VARCHAR,
rules VARCHAR,
availabilitytime VARCHAR,
availabilitysojourn VARCHAR,
availability VARCHAR,
rates VARCHAR,
ratesdescuents VARCHAR,
ratesaditionals VARCHAR,
ratescancellations VARCHAR,
fotos JSONB,
legalinformation VARCHAR,
);

CREATE TABLE typeownhomes (
typeofhousing VARCHAR (50),
numberfloor INTEGER,
numberapartment VARCHAR(25),
lift VARCHAR (25),
garage INTEGER,
numberofrooms INTEGER,
capacitymaxperson VARCHAR,
numberbathrooms INTEGER,
commonareas VARCHAR (100),
kitchen VARCHAR (100),
featuresspecial VARCHAR(200),
comforts VARCHAR,
aditionalservices VARCHAR,
rules VARCHAR,
availabilitytime VARCHAR,
availabilitysojourn VARCHAR,
availability VARCHAR,
rates VARCHAR,
ratesdescuents VARCHAR,
ratesaditionals VARCHAR,
ratescancellations VARCHAR,
fotos JSONB,
legalinformation VARCHAR,
);

